### ISSUE TITLE
Raytracing GLTF fails to vkAllocateDescriptorSets

### ISSUE THREAD

**Issue by spencer-lunarg** [SaschaWillems/Vulkan#1105]
in RADV (Mesa 24) I am seeing `VK_ERROR_OUT_OF_POOL_MEMORY` from the `vkAllocateDescriptorSets` call inside `createDescriptorSets`

It seems the issue is that the Descriptor Set Layout last binding is a 6 bindings (the last being `VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT`) but the Descriptor Pool used is not big enough to hold it

```
Thread 0, Frame 0:
vkCreateDescriptorSetLayout(device, pCreateInfo, pAllocator, pSetLayout) returns VkResult VK_SUCCESS (0):
    device:                         VkDevice = 0x570db5e02ea0
    pCreateInfo:                    const VkDescriptorSetLayoutCreateInfo* = 0x7fffd36f8530:
        sType:                          VkStructureType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO (32)
        pNext:                          const void* = VkDescriptorSetLayoutBindingFlagsCreateInfo
        flags:                          VkDescriptorSetLayoutCreateFlags = 0
        bindingCount:                   uint32_t = 6
        pBindings:                      const VkDescriptorSetLayoutBinding* = 0x570db5fff6b0
            pBindings[0]:                   const VkDescriptorSetLayoutBinding = 0x570db5fff6b0:
                binding:                        uint32_t = 0
                descriptorType:                 VkDescriptorType = VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR (1000150000)
                descriptorCount:                uint32_t = 1
                stageFlags:                     VkShaderStageFlags = 1280 (VK_SHADER_STAGE_RAYGEN_BIT_KHR | VK_SHADER_STAGE_CLOSEST_HIT_BIT_KHR)
                pImmutableSamplers:             const VkSampler* = UNUSED
            pBindings[1]:                   const VkDescriptorSetLayoutBinding = 0x570db5fff6c8:
                binding:                        uint32_t = 1
                descriptorType:                 VkDescriptorType = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE (3)
                descriptorCount:                uint32_t = 1
                stageFlags:                     VkShaderStageFlags = 256 (VK_SHADER_STAGE_RAYGEN_BIT_KHR)
                pImmutableSamplers:             const VkSampler* = UNUSED
            pBindings[2]:                   const VkDescriptorSetLayoutBinding = 0x570db5fff6e0:
                binding:                        uint32_t = 2
                descriptorType:                 VkDescriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER (6)
                descriptorCount:                uint32_t = 1
                stageFlags:                     VkShaderStageFlags = 3328 (VK_SHADER_STAGE_RAYGEN_BIT_KHR | VK_SHADER_STAGE_CLOSEST_HIT_BIT_KHR | VK_SHADER_STAGE_MISS_BIT_KHR)
                pImmutableSamplers:             const VkSampler* = UNUSED
            pBindings[3]:                   const VkDescriptorSetLayoutBinding = 0x570db5fff6f8:
                binding:                        uint32_t = 3
                descriptorType:                 VkDescriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER (1)
                descriptorCount:                uint32_t = 1
                stageFlags:                     VkShaderStageFlags = 1536 (VK_SHADER_STAGE_ANY_HIT_BIT_KHR | VK_SHADER_STAGE_CLOSEST_HIT_BIT_KHR)
                pImmutableSamplers:             const VkSampler* = NULL
            pBindings[4]:                   const VkDescriptorSetLayoutBinding = 0x570db5fff710:
                binding:                        uint32_t = 4
                descriptorType:                 VkDescriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER (7)
                descriptorCount:                uint32_t = 1
                stageFlags:                     VkShaderStageFlags = 1536 (VK_SHADER_STAGE_ANY_HIT_BIT_KHR | VK_SHADER_STAGE_CLOSEST_HIT_BIT_KHR)
                pImmutableSamplers:             const VkSampler* = UNUSED
            pBindings[5]:                   const VkDescriptorSetLayoutBinding = 0x570db5fff728:
                binding:                        uint32_t = 5
                descriptorType:                 VkDescriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER (1)
                descriptorCount:                uint32_t = 15
                stageFlags:                     VkShaderStageFlags = 1536 (VK_SHADER_STAGE_ANY_HIT_BIT_KHR | VK_SHADER_STAGE_CLOSEST_HIT_BIT_KHR)
                pImmutableSamplers:             const VkSampler* = NULL
        pNext:                          VkDescriptorSetLayoutBindingFlagsCreateInfo = 0x7fffd36f8550:
            sType:                          VkStructureType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO (1000161000)
            pNext:                          const void* = NULL
            bindingCount:                   uint32_t = 6
            pBindingFlags:                  const VkDescriptorBindingFlags* = 0x570db5fdaca0
                pBindingFlags[0]:               const VkDescriptorBindingFlags = 0
                pBindingFlags[1]:               const VkDescriptorBindingFlags = 0
                pBindingFlags[2]:               const VkDescriptorBindingFlags = 0
                pBindingFlags[3]:               const VkDescriptorBindingFlags = 0
                pBindingFlags[4]:               const VkDescriptorBindingFlags = 0
                pBindingFlags[5]:               const VkDescriptorBindingFlags = 8 (VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT)
    pAllocator:                     const VkAllocationCallbacks* = NULL
    pSetLayout:                     VkDescriptorSetLayout* = 0x570db60b9420

Thread 0, Frame 0:
vkCreateDescriptorPool(device, pCreateInfo, pAllocator, pDescriptorPool) returns VkResult VK_SUCCESS (0):
    device:                         VkDevice = 0x570db5e02ea0
    pCreateInfo:                    const VkDescriptorPoolCreateInfo* = 0x7fffd36f8580:
        sType:                          VkStructureType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO (33)
        pNext:                          const void* = NULL
        flags:                          VkDescriptorPoolCreateFlags = 0
        maxSets:                        uint32_t = 1
        poolSizeCount:                  uint32_t = 4
        pPoolSizes:                     const VkDescriptorPoolSize* = 0x570db6346ef0
            pPoolSizes[0]:                  const VkDescriptorPoolSize = 0x570db6346ef0:
                type:                           VkDescriptorType = VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR (1000150000)
                descriptorCount:                uint32_t = 1
            pPoolSizes[1]:                  const VkDescriptorPoolSize = 0x570db6346ef8:
                type:                           VkDescriptorType = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE (3)
                descriptorCount:                uint32_t = 1
            pPoolSizes[2]:                  const VkDescriptorPoolSize = 0x570db6346f00:
                type:                           VkDescriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER (6)
                descriptorCount:                uint32_t = 1
            pPoolSizes[3]:                  const VkDescriptorPoolSize = 0x570db6346f08:
                type:                           VkDescriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER (1)
                descriptorCount:                uint32_t = 1
    pAllocator:                     const VkAllocationCallbacks* = NULL
    pDescriptorPool:                VkDescriptorPool* = 0x570db62c1730

Thread 0, Frame 0:
vkAllocateDescriptorSets(device, pAllocateInfo, pDescriptorSets) returns VkResult VK_ERROR_OUT_OF_POOL_MEMORY (-1000069000):
    device:                         VkDevice = 0x570db5e02ea0
    pAllocateInfo:                  const VkDescriptorSetAllocateInfo* = 0x7fffd36f84f0:
        sType:                          VkStructureType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO (34)
        pNext:                          const void* = VkDescriptorSetVariableDescriptorCountAllocateInfo
        descriptorPool:                 VkDescriptorPool = 0x570db62c1730
        descriptorSetCount:             uint32_t = 1
        pSetLayouts:                    const VkDescriptorSetLayout* = 0x570db5d3b400
            pSetLayouts[0]:                 const VkDescriptorSetLayout = 0x570db60b9420
        pNext:                          VkDescriptorSetVariableDescriptorCountAllocateInfo = 0x7fffd36f8540:
            sType:                          VkStructureType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_ALLOCATE_INFO (1000161003)
            pNext:                          const void* = NULL
            descriptorSetCount:             uint32_t = 1
            pDescriptorCounts:              const uint32_t* = 0x7fffd36f84cc
                pDescriptorCounts[0]:           const uint32_t = 15
    pDescriptorSets:                VkDescriptorSet* = 0x570db5d3b3f8
        pDescriptorSets[0]:             VkDescriptorSet = 0

```

**Comment by SaschaWillems** [comment]
Thanks for bringing this up. Interestingly there is no validation error reported, probably due to the ray tracing samples using VK 1.1.

**Comment by spencer-lunarg** [comment]
So I was curious about the lack of Validation error, but looking, I **think** this is valid, if you provide a smaller descriptor pool the `VK_ERROR_OUT_OF_POOL_MEMORY` is the expected behavior

**Comment by SaschaWillems** [comment]
Exactly. It's valid starting with either VK 1.1 or VK 1.0 and one of the maintenance extensions. 

I'll push a fix for this in a moment.

**Comment by SaschaWillems** [comment]
Can you test again. I've just pushed a fix. Kinda embarrassing, I actually read the no. of images but forgot to assign them to the pool size /

**Comment by spencer-lunarg** [comment]
> It's valid starting with either VK 1.1 or VK 1.0 and one of the maintenance extensions

Awww, yes, I know what you mean... I have an internal Validation issue already to start improving these types of warnings, will add this to the list

> Can you test again

It is still failing, the following gets it to work for me

```patch
diff --git a/examples/raytracinggltf/raytracinggltf.cpp b/examples/raytracinggltf/raytracinggltf.cpp
index 65f929a8..bf925b2e 100644
--- a/examples/raytracinggltf/raytracinggltf.cpp
+++ b/examples/raytracinggltf/raytracinggltf.cpp
@@ -524,6 +524,8 @@ public:
                        { VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR, 1 },
                        { VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, 1 },
                        { VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, 1 },
+                       { VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 1 },
+                       { VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1 },
                        { VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, static_cast<uint32_t>(model.textures.size()) }
                };
                VkDescriptorPoolCreateInfo descriptorPoolCreateInfo = vks::initializers::descriptorPoolCreateInfo(poolSizes, 1);
```

**Comment by spencer-lunarg** [comment]
Thanks for the fix! I am still looking into a better way to help make it more obvious you are going to hit a `VK_ERROR_OUT_OF_POOL_MEMORY` for `vkAllocateDescriptorSets` in the VVL

**Comment by SaschaWillems** [comment]
Thanks. Adding a way to detect this via the layers would be very much appreciated :)
